[project]
name = "github_repos_scrapper"
version = "0.1.0"
description = "Github top repositories scrapper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.11.11",
    "aiolimiter==1.2.1",
    "loguru==0.7.3",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]

